language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run build

deploy:
  provider: s3
  access_key_id: 
    secure: "SIVbjcY0qY83IQOKxzsr0ZMvRlYabfRzsMIdGtskZEUa8+C00ypA4PNYOFrJhfIxDqWLXEjo+zMeVjDuisOF9rNwKRAkCyKqUp8VA6kHge72T3mXZTM0WCBzYXXpGoxZrFuJiA2t5PRk/PQLBYbI8uM8jFZb2+xUU0UmkbnnlJjYpsm0wLzXL9nlH5D+S1J6/1zI0OPMPQYfuzlPHVi9SLGCrLg9ft3ez9dsoTzzo7gD2xlsZORRThbkCuMHLNjvvzkOhIZGlYi5gOh7RDg4Fwntu1wnJ+MYyrqehyDQofdxX+F4tdqc1ErAbSnangArsXnGXx7PgrjkPoCzChXrxRZk3SmHYfQnJs9FvmJ9mcKuvVsw1RqO5LAzdZnv1J/w+gTtdhHTi68i5KxqiwbcZtlq1ZDMEqBdQ8bLIKWIZUWgJ8+dDXaCdCbrkooDPzylOJtIp+xyZL/p/Uo0aNBVEuIB7p6okpr7Q1FX/SNO+epdSCxo3mmM5AEbW4RFVGFlA6A1WKCn0z+/4a0GLdiHOP2J7XM+U/qjxrZbOQ70qfdJY/K0hJsES8UnLd0+We3yVDA9j5dTUFP6/mUJ6lIg27DFQIe+eF2FrPJ93S42DP+bFuHnh2+KYB6MI19PSZnnldMjXhlALvHv+H33FmYc1kwsSf09lCy4CKiPOvGI2TQ="
  secret_access_key:
    secure: "nyzdfCxvqVH7f4XWxKJUx/SM3c4smhcqDJZKqriPNzUE3IY7th/uIHX9WUcnAtk0c8S0cfv3pLZFTmkMUA62JmhZKLJJ1P4GvrXX+c6kSPx7MV27mRdCDeBgS5ZNEdGKm/KIfOHXYczfuUDGxc3Jqvwn9MU7mLq7j8j9rxMOySyV2HflmCHW3ICEe09gkDNby7UjiEJgPDRfzn3d9JQw78bddspHyIdeZvQjvqYIlNpuLRO4QBg5ggFtajzC3iqQOCrowU+0jbfpiP7k82hagV4YyzTnradc6SgHpuFLMzcXBnz6TfD1+hc9azHo9E3tMbgllhZ08HRjEq0SNCA/XMxk0WDQsZC3tiQ/SNICaumtXzHFLclnvBbxAq9xMyD1yir0ReBYm5TeEIU7fphnd5xt6YADbgzyky3PQcOFRgalcMPUmzH/wvL+vQy/QvM+JZGYLgwanNHZtUk5PMuozzGMoH2iMTtwYSyWzCzhqolxJxyREkCil5F6vTb1bM1AkFdMWlNb+wRXYUOYTP4TBklO/7LXmMfWxMCXLl1JweAk+QvRBj4QEAqHWX5tkoQOijzskAYbwOCNMXhl3jV4ZqION79Y3s/QbcndgN8sNxa0xEVdq36LGabSnId+6YGwZoA5tQrFSzQ8Ta0ziQIyD5PDqNRJNYx2FbLrUxLdmXE="
  bucket: nadeploy
  region: eu-central-1
  local_dir: build
  skip_cleanup: true
  on:
    all_branches: true