language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run build

deploy:
  provider: s3
  access_key_id: 
   secure: SIVbjcY0qY83IQOKxzsr0ZMvRlYabfRzsMIdGtskZEUa8+C00ypA4PNYOFrJhfIxDqWLXEjo+zMeVjDuisOF9rNwKRAkCyKqUp8VA6kHge72T3mXZTM0WCBzYXXpGoxZrFuJiA2t5PRk/PQLBYbI8uM8jFZb2+xUU0UmkbnnlJjYpsm0wLzXL9nlH5D+S1J6/1zI0OPMPQYfuzlPHVi9SLGCrLg9ft3ez9dsoTzzo7gD2xlsZORRThbkCuMHLNjvvzkOhIZGlYi5gOh7RDg4Fwntu1wnJ+MYyrqehyDQofdxX+F4tdqc1ErAbSnangArsXnGXx7PgrjkPoCzChXrxRZk3SmHYfQnJs9FvmJ9mcKuvVsw1RqO5LAzdZnv1J/w+gTtdhHTi68i5KxqiwbcZtlq1ZDMEqBdQ8bLIKWIZUWgJ8+dDXaCdCbrkooDPzylOJtIp+xyZL/p/Uo0aNBVEuIB7p6okpr7Q1FX/SNO+epdSCxo3mmM5AEbW4RFVGFlA6A1WKCn0z+/4a0GLdiHOP2J7XM+U/qjxrZbOQ70qfdJY/K0hJsES8UnLd0+We3yVDA9j5dTUFP6/mUJ6lIg27DFQIe+eF2FrPJ93S42DP+bFuHnh2+KYB6MI19PSZnnldMjXhlALvHv+H33FmYc1kwsSf09lCy4CKiPOvGI2TQ=
  secret_access_key:
    secure: CIvcZdctvR4xJ8MvcDP0WasaV0/i7m4IjJIagXhF2IBCqDkQD5BqQsbRiy1ZdXdV9kc5DCW/SnpAu+ygF+5+/QGT6M2e1D+gJFPgom02u10bvV/piYxyLECbLhmoGYEVFwrsu7SRtepXUqXMamjERuYjVMX+SGaFtzohP27npcOp9/gBbRnF4kEdDsISz0H3IRaj3foEfzHHdyepMUHvvzlyYgN7cvRNA/8E2FHAzO6b+P9u6Autunt+4+uoEWVw8jSSjGMQDVBelUnTEwHMoR/bm3MO+/bj4dFkNDrzTcK25JU2gFMJxmPUlvuIlz7nZI5wuAIGQLz8A/K8pDuJUKCYtFt1jeXzk5smdHqd52QuMqyQnC0x2IEqonDQpDzdFfKuNpqsL18CNOtdkgMQQsIxPJkFNz1cQvm+08SWCPE/jhZ+gXAAgXQbIOfTqidmCBWeFJYlscHS86qdJUOqcyMRi5qeTbssNn97PMf3qIqGgZXeKG8JZRDB6G7sQXs0x7qoNSFnczUGqo+FK/H2um8XZumdWstl3z+xCKjWenhlrfYKiypYlATUNb9iBEQp70iw3+rB3VFde2QWoK2/BqDZzP+tV9DI1ZvtOjriGRKZJ+Aph6J/UEKDBoueO9yKVfup1GfONE4z8108Ydxu3qxSxfIe47B2Lx9tkatRAJ8=
  bucket: nadeploy
  region: eu-central-1
  local_dir: build
  skip_cleanup: true
  on:
    all_branches: true