language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run build

deploy:
  provider: s3
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: nadeploy
  region: eu-central-1
  local_dir: build
  skip_cleanup: true
  on:
    all_branches: true