language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run build

deploy:
  provider: s3
  access_key_id: 
    secure: Q7rRCmc2pih1wWYDFBxgEKtNu1O4gbTYTAnzBiwmqeqKrD7mBiC4z3Nd95BA/1e2gfkeZs4fVXn1jymrdeBpVIl8xFzEK4bcyqk7L0S6j9oVFOElF8HxYqznp+FhTfi8U+iYG6n/PkwQT1U8qOsoK9yZqtSdQsSqH1rcNTOPXNlihwCMkbefpFKR0t2mS5gRRrJSN9ModPIObOe60QUqnO86arbGlh1a9ytn/HElM08eanQfvrb9b+5cYbo4vh4EpKP9Kjm3KPUnBDVoJeXrWFQYE/qblYZtBO3oX58IBMbOK8csYXIb54OWVcgaVrTD8NbmIgDA6rGX5TQ2QGxGDEs38EKIb+huQ29aSTHXImeWXe+NJJJ2U8o2zlpFZGPpADkm4t6xqPkz8jodBtpJ8HgSQmbnEt5s/9xM1zAupcfY30AO9jWolM+qMFuo6xKn7vnKITwDbmJ3PX03hDVqL7H5H+rYwDDqApurahhvegFhsGrHcq1NmOxycdchRjoEG2KvVtWUYg4RSWGJvkWzoflisWcPlPEoH+HhAKEA0Cy5ROVe+QdZTtr7k8gtc26FkkgciM/TM14lm2BYtJ6KSZ8P7oPoNH6+Sn6auc0urcDgsg3j8SoFelb69cKJoO2Ul7k0X3cx2cGbnv9ujRHH/XI1LnIlTW1XlR18KC8cFzI=
  secret_access_key:
    secure: CQJPDapDjHsmT8ZNiMCvPR61mAUOyCC8I7qCqD3AbfdMX2TdUFDJJZGKJvLp3EuqvSrjsZBzTquohOVkkacaP8TpHDf2pahEbt/9P4+edAj6/+96fW1wFOmwm61bf1ZUCRAEGTaYKa7L6nfNkKCtFSXkgaTCQWU9o4GbVTgzaGj7nor4mx4l1AbXpgknhDH8/HRwGPoAcvgmR5jSRrkbLHLkg1eOzVM7RQM064UXdwALm49e33q9FiHWssbaQZj8O8J9knGaqqUotsuSeTx3R7Zr+tWidtjXtCwM8u+MVWEj2cAmkm/U6UWx9ynUU/BeJ+b/Uw8LpnXo1WDI1kPi3BiVcdxUK49LD3xZK9Sy3ZIXIKXSw1N8nHEGwpPPREg4yDvpA5vc2sgp/BkLatnxDp9RPP9FTiCYKtpEJh1iGebTP9WmdXOjiKRlLD8P6qApZW+gDQ5Wt9OkbgiMidETXVRBpF8yOshNXfoq3CQdI/C7iYSR7liQvW9qIe/pCAsC8BTm0Lf3yYGi7aXbJWQT0D1D+FK5I32BTSBox7Nmkz+DD0G9Iq/RkuMj9NANfwq9asLmb1S7VSN05WIGJrKyC0BKLgS7/Og22qmawLSUK4I+ZciKUS8lBNPQHH9trOh2cwN4qDUCjIt/7XZI7wS36Yg8Kt8w/jqPFFEec55iMn8=
  bucket: nadeploy
  local_dir: build
  skip_cleanup: true
  on:
    all_branches: true